<?php
define('FB_APIKEY', '339554932739410');
define('FB_SECRET', '8f2b6ac74a46e8bbfad235fa87bd6962');
define('FB_SESSION', 'YOUR_SESSION_key');
require_once('facebook-platform/php/facebook.php');
try {
	$facebook = new Facebook(FB_APIKEY, FB_SECRET);
	$facebook->api_client->session_key = FB_SESSION;
	$fetch = array('friends' =>
	array('pattern' => '.*',
	'query' => "select uid2 from friend where uid1={$user}"));
	echo $facebook->api_client->admin_setAppProperties(array('preload_fql' => json_encode($fetch)));
	$message = "[This status is generated by the robot]\n";
	$message .= "Pengumpulan status dimulai";
	if( $facebook->api_client->stream_publish($message))
	echo "[Status Berhasil Digenerate]";
} catch(Exception $e) {
echo $e . "<br />";
}
?>